// <auto-generated />
namespace ShitpostTron5000.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class messageachrive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messageachrive));
        
        string IMigrationMetadata.Id
        {
            get { return "201711161504418_messageachrive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
